using UnityEngine;
using UnityEditor;
using UnityEditor.Animations;
using System.IO;
using System.Collections.Generic;

public static class CharacterPrefabCreator
{
    // Shared assets
    private const string ControllerPath   = "Assets/Prefabs/Characters/PlayerAnimator.controller";
    private const string PlayerConfigPath = "Assets/Prefabs/Characters/PlayerConfig.asset";

    [MenuItem("Tools/Characters/Create Character Prefab From Selected FBX")]
    public static void CreateCharacterPrefabFromSelectedFbx()
    {
        var selected = Selection.activeObject as GameObject;
        if (selected == null)
        {
            Debug.LogError("Select a character FBX in the Project window first.");
            return;
        }

        string fbxPath = AssetDatabase.GetAssetPath(selected);
        if (!fbxPath.EndsWith(".fbx", System.StringComparison.OrdinalIgnoreCase))
        {
            Debug.LogError("Selected asset is not an FBX: " + fbxPath);
            return;
        }

        // 1) Ensure materials & textures are extracted to subfolders
        EnsureExtractedAssets(fbxPath);

        AutoAssignAlbedoTextures(fbxPath);

        // 2) Instantiate a temporary instance
        var instance = PrefabUtility.InstantiatePrefab(selected) as GameObject;
        if (instance == null)
        {
            Debug.LogError("Failed to instantiate FBX.");
            return;
        }

        // Remove any cameras/lights that came from the FBX
        foreach (var cam in instance.GetComponentsInChildren<Camera>(true))
        {
            Object.DestroyImmediate(cam.gameObject);
        }

        foreach (var light in instance.GetComponentsInChildren<Light>(true))
        {
            Object.DestroyImmediate(light.gameObject);
        }

        instance.name = Path.GetFileNameWithoutExtension(fbxPath);

        // --- CharacterController ---
        var cc = instance.GetComponent<CharacterController>();
        if (cc == null)
        {
            cc = instance.AddComponent<CharacterController>();
            cc.height = 2f;
            cc.radius = 0.5f;
            cc.center = new Vector3(0f, 1f, 0f);
        }

        // --- PlayerController (playable) ---
        var playerController = instance.GetComponent<PlayerController>();
        if (playerController == null)
        {
            playerController = instance.AddComponent<PlayerController>();
        }

        var characterMotor = instance.GetComponent<CharacterMotor>();
        if (characterMotor == null)
        {
            characterMotor = instance.AddComponent<CharacterMotor>();
        }

        // --- Animator ---
        var animator = instance.GetComponentInChildren<Animator>();
        if (animator == null)
            animator = instance.AddComponent<Animator>();

        var controller = AssetDatabase.LoadAssetAtPath<AnimatorController>(ControllerPath);
        if (controller == null)
        {
            Debug.LogError("Could not find PlayerAnimator.controller at: " + ControllerPath);
        }
        else
        {
            animator.runtimeAnimatorController = controller;
        }

        // Assign avatar generated by FBX import
        var modelRoot = AssetDatabase.LoadAssetAtPath<GameObject>(fbxPath);
        if (modelRoot != null)
        {
            var avatar = modelRoot.GetComponent<Animator>()?.avatar;
            if (avatar != null)
            {
                animator.avatar = avatar;
            }
            else
            {
                Debug.LogWarning("No avatar found on model root. Ensure FBX rig is Humanoid.");
            }
        }

        // --- Ensure / assign PlayerConfig ScriptableObject ---
        var config = AssetDatabase.LoadAssetAtPath<PlayerConfig>(PlayerConfigPath);
        if (config == null)
        {
            config = ScriptableObject.CreateInstance<PlayerConfig>();

            // Ensure folders exist for PlayerConfigPath
            var dir = Path.GetDirectoryName(PlayerConfigPath).Replace("\\", "/");
            EnsureFolderPath(dir);

            AssetDatabase.CreateAsset(config, PlayerConfigPath);
            AssetDatabase.SaveAssets();
            Debug.Log("Created new PlayerConfig asset at: " + PlayerConfigPath);
        }

        if (playerController != null && config != null)
        {
            var so = new SerializedObject(playerController);
            var prop = so.FindProperty("config"); // field name in PlayerController
            if (prop != null)
            {
                prop.objectReferenceValue = config;
                so.ApplyModifiedPropertiesWithoutUndo();
            }
            else
            {
                Debug.LogWarning("PlayerController has no serialized field named 'config'. " +
                                 "Update CharacterPrefabCreator if the field name is different.");
            }
        }

        // Tag (optional)
        instance.tag = "Player";

        // --- Save prefab next to the FBX ---
        string fbxDir = Path.GetDirectoryName(fbxPath).Replace("\\", "/");
        string prefabPath = Path.Combine(fbxDir, instance.name + ".prefab").Replace("\\", "/");

        PrefabUtility.SaveAsPrefabAssetAndConnect(instance, prefabPath, InteractionMode.UserAction);
        Object.DestroyImmediate(instance);

        Debug.Log($"Created character prefab at: {prefabPath}");
    }

    private static void AutoAssignAlbedoTextures(string fbxPath)
    {
        string fbxDir = Path.GetDirectoryName(fbxPath).Replace("\\", "/");
        string materialsDir = fbxDir + "/Materials";
        string texturesDir  = fbxDir + "/Textures";

        if (!AssetDatabase.IsValidFolder(materialsDir) || !AssetDatabase.IsValidFolder(texturesDir))
            return;

        // Load all extracted materials + textures
        var materials = Directory.GetFiles(materialsDir, "*.mat", SearchOption.TopDirectoryOnly);
        var textures  = Directory.GetFiles(texturesDir, "*.*", SearchOption.TopDirectoryOnly);

        // Load Texture2D assets
        var texAssets = new List<Texture2D>();
        foreach (var t in textures)
        {
            var tex = AssetDatabase.LoadAssetAtPath<Texture2D>(t);
            if (tex != null)
                texAssets.Add(tex);
        }

        if (texAssets.Count == 0)
            return;

        // Pick an albedo candidate
        Texture2D PickAlbedo(List<Texture2D> texs)
        {
            // look for typical albedo naming patterns
            string[] keywords = { "albedo", "diff", "basecolor", "color" };

            foreach (var tex in texs)
            {
                string name = tex.name.ToLower();
                foreach (var k in keywords)
                    if (name.Contains(k))
                        return tex;
            }

            // fallback: just use first texture
            return texs[0];
        }

        Texture2D albedo = PickAlbedo(texAssets);

        // Assign albedo to each material if missing
        foreach (var matPath in materials)
        {
            var mat = AssetDatabase.LoadAssetAtPath<Material>(matPath);
            if (mat == null) continue;

            // Only assign if missing
            if (!mat.HasProperty("_MainTex")) continue;
            if (mat.GetTexture("_MainTex") != null) continue;

            mat.SetTexture("_MainTex", albedo);
            EditorUtility.SetDirty(mat);
        }

        AssetDatabase.SaveAssets();
        Debug.Log("Auto-assigned albedo texture(s) for: " + fbxPath);
    }


    /// <summary>
    /// Create Materials/ and Textures/ under the FBX folder,
    /// extract embedded materials and textures into them.
    /// </summary>
    private static void EnsureExtractedAssets(string fbxPath)
    {
        var importer = AssetImporter.GetAtPath(fbxPath) as ModelImporter;
        if (importer != null)
        {
            importer.animationType = ModelImporterAnimationType.Human;
            importer.avatarSetup = ModelImporterAvatarSetup.CreateFromThisModel;
            importer.SaveAndReimport();
        }
        else
        {
            Debug.LogError("Could not get ModelImporter for FBX: " + fbxPath);
            return;
        }

        string fbxDir = Path.GetDirectoryName(fbxPath).Replace("\\", "/");
        string materialsDir = fbxDir + "/Materials";
        string texturesDir  = fbxDir + "/Textures";

        EnsureFolderPath(materialsDir);
        EnsureFolderPath(texturesDir);

        // Extract embedded textures (if any)
        try
        {
            importer.ExtractTextures(texturesDir);
        }
        catch
        {
            // Not fatal; some FBXs just don't have embedded textures
        }

        // Extract embedded materials as .mat assets
        Object[] subAssets = AssetDatabase.LoadAllAssetsAtPath(fbxPath);
        bool extractedMat = false;

        foreach (var asset in subAssets)
        {
            if (asset is Material mat)
            {
                string targetPath = Path.Combine(materialsDir, mat.name + ".mat").Replace("\\", "/");
                targetPath = AssetDatabase.GenerateUniqueAssetPath(targetPath);

                AssetDatabase.ExtractAsset(mat, targetPath);
                extractedMat = true;
            }
        }

        if (extractedMat)
        {
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }

        // Reimport so the FBX now references external materials/textures
        importer.SaveAndReimport();
    }

    /// <summary>
    /// Ensures a folder path like "Assets/Prefabs/Characters/Players/old_man/Materials" exists.
    /// </summary>
    private static void EnsureFolderPath(string fullPath)
    {
        // Expect something like "Assets/Prefabs/Characters/Players/old_man/Materials"
        var parts = fullPath.Split('/');
        if (parts.Length == 0) return;

        string current = parts[0];
        for (int i = 1; i < parts.Length; i++)
        {
            string next = current + "/" + parts[i];
            if (!AssetDatabase.IsValidFolder(next))
                AssetDatabase.CreateFolder(current, parts[i]);
            current = next;
        }
    }
}
